services:
  - type: web
    name: sangoma-webside
    env: python
    plan: free
    region: oregon
    branch: main
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi
    releaseCommand: python manage.py migrate
    envVars:
      - key: DEBUG
        value: "false"
databases:
  - name: sangoma-db
    plan: starter
    region: oregon
