# Generated by Django 6.0.5 on 2026-06-01 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dailymessagecomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymessage',
            name='active',
            field=models.BooleanField(default=True, help_text='Tick this to show the message. Untick to hide it.'),
        ),
        migrations.AlterField(
            model_name='dailymessage',
            name='text',
            field=models.TextField(help_text="Type today's encouragement message here."),
        ),
        migrations.AlterField(
            model_name='dailymessagecomment',
            name='text',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='DailyMessageShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='core.dailymessage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('daily_message', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('❤️', 'Love'), ('🙏', 'Grateful'), ('✨', 'Inspired'), ('😢', 'Touched'), ('🔥', 'Powerful')], max_length=10)),
                ('daily_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.dailymessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('daily_message', 'user')},
            },
        ),
    ]
